### ISSUE TITLE
Headless Mode and Download Dir not working in Chrome 110

### ISSUE THREAD

**Issue by aslanonline** [php-webdriver/php-webdriver#1053] opened 2023-02-18 12:54 UTC
### Bug description

Hello,

I am using latest php-webdriver and also Chrome/Webdriver 110 Version.
There is  a known bug that download.default_directory not working in --headless mode.
The Workaround is to use --headless=new. But after using it as argument Chrome gets a crash.

`Timeout Exception becauseunknown error: Chrome failed to start: crashed. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) `

### How could the issue be reproduced

```shell
$chromeOptions->addArguments(['--disable-gpu','--headless=new','--no-sandbox','--incognito','--user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36    "']);

$prefs = array('download.default_directory' => $dir);
```

### Php-webdriver version

1.14.0

### PHP version

8.1.16

### How do you start the browser driver or Selenium server

chromedriver --port=4444

### Browser driver (chromedriver/geckodriver...) version

110.0.5481.77

### Browser name and version

110.0.5481.100

### Operating system

Debian

**Comment by ramondelafuente** [comment] 2023-03-07 16:22
We're also experiencing problems with the `download.default_directory` not working. Oddly enough, everything was working fine in `Chrome/Webdriver 108`. All downloads now end up in the working directory (the directive seems to be ignored).
I'm not completely sure what the root cause is, or if it's a known problem, or even if it can be fixed by this library. But I thought I'd add here and keep track of any updates or mentions on this issue.

**Comment by aslanonline** [comment] 2023-03-07 16:23
Hello, 
for this issue use --headless=new as Argument

**Closed** 2023-03-19 19:20 UTC
Labels: bug
