### ISSUE TITLE
Cannot set cookie for single label domain name

### ISSUE THREAD

**Issue by vctls** [php-webdriver/php-webdriver#763] opened 2020-02-13 09:46 UTC
### What are you trying to achieve? (Expected behavior)
Setting a cookie for the domain corresponding to my web server container, for example: `my_app_nginx`.

I'm running a multi-container docker-compose project and I want to run Codeception tests with coverage. Codeception needs to set a cookie for that.

### What do you get instead? (Actual behavior)
An `UnableToSetCookieException`.
```
Facebook\WebDriver\Exception\UnableToSetCookieException] unable to set cookie
```

### How could the issue be reproduced? (Steps to reproduce)
Try to set a cookie for a single label domain.

### Details

* Php-webdriver version: 1.8.0
* PHP version: 7.2
* Selenium server version: selenium-chrome-standalone 3.141.59 Docker image
* Operating system: image uses Ubuntu 18.04.3 LTS
* Browser used + version: Chrome 79.0.3945.117

I didn't have that issue before I updated Codeception and Php-Webdriver.
Changing the web server container name to `my_app_nginx.local` solves the issue.
It was this Firefox issue that made me think of changing the domain:
https://bugzilla.mozilla.org/show_bug.cgi?id=1488225

**Comment by OndraM** [comment] 2020-02-13 16:14
I can confirm the issue on both latest ChromeDriver 80.0.3987.87 and Firefox/Geckodriver 0.26 .

However - this does not seem like an issue in php-webdriver, but rather a design choice in the browser implementation.

Chrome does not allow setting cookies for localhost domains: https://bugs.chromium.org/p/chromium/issues/detail?id=56211
And the issue in Firefox you already linked is https://bugzilla.mozilla.org/show_bug.cgi?id=1488225 (and it also seems to be related to https://github.com/mozilla/geckodriver/issues/1521)

If the host you use always refer to localhost, you can just add postfix "foo.localhost" to make it reference your localhost. Or you can omit setting the domain entirely, which will cause it to be set for current domain.

**Comment by vctls** [comment] 2020-02-13 18:17
Well, in my case it doesn't refer to localhost but to the IP address of the web server container in the internal docker-compose project network.
If it really is an issue with the browsers, I don't mind this issue being closed. As I said I can just rename my container to `something.foo` and it works.

The weird thing is, if I didn't mix up my commits, I started getting this with Chrome only after updating Codeception and with it Php-Webdriver, while my selenium-chrome container stayed on version 3.141.59…
Also, not sure if that Chrome issue is just for `localhost` or any single label domain.

I could try downgrading Php-WebDriver and check my Chrome version, just to be sure.

**Comment by OndraM** [comment] 2020-02-14 00:00
I tried with non-localhost domain without dot and the issue is the same.  But it may be expected behavior...

It is possible the issue appears with php-webdriver 1.8.0, because it by default use W3C WebDriver protocol. And the implementation in Chromedriver could be different for the new protocol.

I suggest reporting this to Chromium and attach verbose log from Selenium/Chromedriver - I don't see what could be done on php-webdriver side, so closing this for now.

**Closed by OndraM** 2020-02-14 00:00 UTC

**Comment by Naktibalda** [comment] 2020-03-22 16:06
I raised pull request to stop setting domain names in setCookie: https://github.com/Codeception/module-webdriver/pull/10
