### ISSUE TITLE
Chrome Option "mobileEmulation" not working

### ISSUE THREAD

**Issue by oluethje** [php-webdriver/php-webdriver#910] opened 2021-05-28 09:43 UTC
I using php-webdriver with docker-selenium (hub and node-chrome) and wanted to use the mobile device emulation. Following the instructions found in tutorials I define the Option via:

```php
$options = new ChromeOptions();
$options->addArguments([
    '--no-sandbox',
    '--ignore-certificate-errors',
    '--disable-notifications',
    '--headless',
    '--user-agent SeleniumWebDriver',
]);

$mobile_emulation = ['deviceName' => 'iPhone 6 Plus'];
$options->setExperimentalOption('mobileEmulation', $mobile_emulation);

$capabilities = DesiredCapabilities::chrome();
$capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

self::$webDriver = RemoteWebDriver::create(
    self::SELENIUM_HUB_URL,
    $capabilities
);
```

But the browser did not use the emulation. Screenshots showed the desktop version of the website.

After trying out different versions and examples i started debugging in php-webdriver and found that in \Facebook\WebDriver\Remote\HttpCommandExecutor::execute() the $encodedParams value used as POST request for the session initialization was:

```json
{
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "mobileEmulation": {
            "deviceName": "iPhone 6 Plus"
          },
          "args": [
            "--no-sandbox",
            "--ignore-certificate-errors",
            "--disable-notifications",
            "--headless",
            "--user-agent SeleniumWebDriver"
          ]
        }
      }
    ]
  },
  "desiredCapabilities": {
    "browserName": "chrome",
    "platform": "ANY",
    "chromeOptions": {
      "mobileEmulation": {
        "deviceName": "iPhone 6 Plus"
      },
      "args": [
        "--no-sandbox",
        "--ignore-certificate-errors",
        "--disable-notifications",
        "--headless",
        "--user-agent SeleniumWebDriver"
      ]
    }
  }
}
```

The difference between "goog:chromeOptions" in the "firstMatch" section and the "chromeOptions" in "desiredCapabilities" seemed strange to me. I found that the change of "chromeOptions" to "goog:ChromeOptions" has been an issue in the past.

I changed:

`        $parameters['desiredCapabilities'] = (object) $desired_capabilities->toArray();
`
in \Facebook\WebDriver\Remote\RemoteWebDriver::create() to

`        $parameters['desiredCapabilities'] = (object) $desired_capabilities->toW3cCompatibleArray();
`

resulting in a different parameters object:

```json
{
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "mobileEmulation": {
            "deviceName": "iPhone 6 Plus"
          },
          "args": [
            "--no-sandbox",
            "--ignore-certificate-errors",
            "--disable-notifications",
            "--headless",
            "--user-agent SeleniumWebDriver"
          ]
        }
      }
    ]
  },
  "desiredCapabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "mobileEmulation": {
        "deviceName": "iPhone 6 Plus"
      },
      "args": [
        "--no-sandbox",
        "--ignore-certificate-errors",
        "--disable-notifications",
        "--headless",
        "--user-agent SeleniumWebDriver"
      ]
    }
  }
}
```

With this parameter hash the browser uses the mobile emulation as expected.

I'm not an expert in php-webdriver and unsure if this change might affect other browsers.

### Details
* Php-webdriver version: 1.11.1
* PHP version:  7.2
* How do you start the browser driver or Selenium server:
  docker-selenium from docker-hub: selenium/hub:latest and selenium/node-chrome:latest
* Selenium server version: v.3.141.59
* Browser driver chromedriver) version: v:90.0.4430.85
* Operating system: linux

Is this a bug and if so, is the change to toW3cCompatibleArray() a working solution for all node types and versions?

**Comment by OndraM** [comment] 2022-08-25 14:42
Closing this for now, as the issue is old and may no longer be relevant in current versions. Also I was unable to reproduce it. 

However, if it is still present in latest Selenium server and latest Chrome/Chromedriver, feel free to open a new issue.

Thanks for your understanding.

**Closed** 2022-08-25 14:42 UTC
Labels: bug

**Comment by oluethje** [comment] 2022-08-31 14:04
thanks for your work. I'll try to reproduce this with current versions soon.
