### ISSUE TITLE
Bug #848

### ISSUE THREAD

**Issue by kenygamer** [php-webdriver/php-webdriver#851] opened 2020-12-30 05:43 UTC
I urge a reply to my issue #848. It was turned into a discussion but I didn't really want to downplay it. 

I am late in tons of paid projects, and compensations are becoming unaffordable right now. I can't advance without webdriver working.

**Comment by andrewnicols** [comment] 2020-12-30 06:30
Closing this issue as it is not a bug but a configuration issue.

**Closed by andrewnicols** 2020-12-30 06:30 UTC
Labels: bug

**Comment by kenygamer** [comment] 2020-12-30 19:17
> Closing this issue as it is not a bug but a configuration issue.

Please help me when you can.

**Comment by kenygamer** [comment] 2021-01-02 07:55
@andrewnicols It's ok, but I came to open an issue after a week of trying to fix it on my own, my issue becomes a discussion. I needed this more than two weeks ago, is it possible to get help faster?  If it's a configuration issue, what can I do if your guide isn't clear enough?

**Comment by kenygamer** [comment] 2021-01-03 16:15
I appreciate your attention.

**Comment by OndraM** [comment] 2021-01-07 18:18
@kenygamer Please note this project is maintained by unpaid volunteers in their free time. Sorry to hear it affect *your* paid projects, but there is nothing we can do except trying to help you in https://github.com/php-webdriver/php-webdriver/discussions/848 - but this is no commercial support with guaranteed reply times, its just a community help.

Also - of there is something in README or wiki what could be improved, you can always send a pull request and help improving it.

Thanks for your understanding.
