### ISSUE TITLE
HttpCommandExecutor receives sessionId from Selenium, but still throws unknown error

### ISSUE THREAD

**Issue by LaraGastaldi** [php-webdriver/php-webdriver#1099] opened 2024-06-20 13:13 UTC
### Bug description

I am using PHP 8.1, Laravel, Laradock (Docker) with a Selenium container, php-webdriver in the latest version (1.15.1) and Laravel Dusk. I tried running the very basic example test from Dusk.
I've made some dd( )s in the HttpCommandExecutor file and I noticed the curl command returns a valid JSON for the Selenium call. Still, the curl_error returns an unknown error. I also made the curl call myself and the Selenium server is working as expected.

This is the Selenium response got in the HttpCommandExecutor (variable `$raw_results`, in the "execute" method):

```
{
  "value": {
    "sessionId": "7a7e3445829f3f4840630a6e23b8584b",
    "capabilities": {
      "acceptInsecureCerts": false,
      "browserName": "chrome-headless-shell",
      "browserVersion": "125.0.6422.76",
      "chrome": {
        "chromedriverVersion": "125.0.6422.76 (67dcf7562b8fb4ab0819135589e37a97bcc8942c-refs\u002fbranch-heads\u002f6422@{#1086})",       
        "userDataDir": "\u002ftmp\u002f.org.chromium.Chromium.dxmgRQ"
      },
      "fedcm:accounts": true,
      "goog:chromeOptions": {
        "debuggerAddress": "localhost:44235"
      },
      "networkConnectionEnabled": false,
      "pageLoadStrategy": "normal",
      "platformName": "linux",
      "proxy": {
      },
      "se:bidiEnabled": false,
      "se:cdp": "ws:\u002f\u002f172.23.0.2:4444\u002fsession\u002f7a7e3445829f3f4840630a6e23b8584b\u002fse\u002fcdp",
      "se:cdpVersion": "125.0.6422.76",
      "se:vnc": "ws:\u002f\u002f172.23.0.2:4444\u002fsession\u002f7a7e3445829f3f4840630a6e23b8584b\u002fse\u002fvnc",
      "se:vncEnabled": true,
      "se:vncLocalAddress": "ws:\u002f\u002f172.23.0.2:7900",
      "setWindowRect": true,
      "strictFileInteractability": false,
      "timeouts": {
        "implicit": 0,
        "pageLoad": 300000,
        "script": 30000
      },
      "unhandledPromptBehavior": "dismiss and notify",
      "webauthn:extension:credBlob": true,
      "webauthn:extension:largeBlob": true,
      "webauthn:extension:minPinLength": true,
      "webauthn:extension:prf": true,
      "webauthn:virtualAuthenticators": true
    }
  }
}
```

And this is the first error got by `curl_error($this->curl)` right after `$raw_results` getting:
`{"value":{"error":"unknown error","message":"unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=125.0.6422.76)","stacktrace":"#0 0x55d7213fee9a \u003Cunknown>\n#1 0x55d7210e845c \u003Cunknown>\n#2 0x55d7210dffd0 \u003Cunknown>\n#3 0x55d7210cfb32 \u003Cunknown>\n#4 0x55d7210d1162 \u003Cunknown>\n#5 0x55d7210cfded \u003Cunknown>\n#6 0x55d7210cf503 \u003Cunknown>\n#7 0x55d7210cf3f5 \u003Cunknown>\n#8 0x55d7210cd336 \u003Cunknown>\n#9 0x55d7210cd83a \u003Cunknown>\n#10 0x55d7210eaea7 \u003Cunknown>\n#11 0x55d721176ed5 \u003Cunknown>\n#12 0x55d7211574b2 \u003Cunknown>\n#13 0x55d7211762cc \u003Cunknown>\n#14 0x55d721157253 \u003Cunknown>\n#15 0x55d7211271c7 \u003Cunknown>\n#16 0x55d721127b3e \u003Cunknown>\n#17 0x55d7213c52db \u003Cunknown>\n#18 0x55d7213c9387 \u003Cunknown>\n#19 0x55d7213b1e0e \u003Cunknown>\n#20 0x55d7213c9e52 \u003Cunknown>\n#21 0x55d7213967af \u003Cunknown>\n#22 0x55d7213ee188 \u003Cunknown>\n#23 0x55d7213ee35b \u003Cunknown>\n#24 0x55d7213fdfcc \u003Cunknown>\n#25 0x7f74a88b7ac3 \u003Cunknown>\n"}}`

Response from Dusk:
```
 FAIL  Tests\Browser\ExampleTest
  ⨯ basic example                                                                                                                    0.73s  
  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  
   FAILED  Tests\Browser\ExampleTest > basic example                                                                UnknownErrorException   
  unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome-headless-shell=125.0.6422.76)

  at vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:146
    142▕                     throw new UnexpectedAlertOpenException($message, $results);
    143▕                 case 'unknown command':
    144▕                     throw new UnknownCommandException($message, $results);
    145▕                 case 'unknown error':
  ➜ 146▕                     throw new UnknownErrorException($message, $results);
    147▕                 case 'unknown method':
    148▕                     throw new UnknownMethodException($message, $results);
    149▕                 case 'unsupported operation':
    150▕                     throw new UnsupportedOperationException($message, $results);

      +5 vendor frames 
  6   tests/Browser/ExampleTest.php:17
  7   tests/Browser/ExampleTest.php:19


  Tests:    1 failed (0 assertions)
  Duration: 1.02s
```
Meanwhile I'll extend the HttpCommandExecutor and the RemoteWebDriver to ignore this error, or else I won't be able to move forward.

What may I be doing wrong?

### How could the issue be reproduced

```shell
/**
     * Create the RemoteWebDriver instance.
     */
    protected function driver(): RemoteWebDriver
    {
        $options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
            '--headless=new',
            '--headless',
            '--no-sandbox',
            '--ignore-ssl-errors',
            '--whitelisted-ips=""'
        ]);

        return RemoteWebDriver::create(
            'http://selenium:4444/wd/hub', desired_capabilities: DesiredCapabilities::chrome()->setCapability(
            ChromeOptions::CAPABILITY, $options
        ));
    }
```

### Expected behavior

Expected the ExampleTest of Dusk to run

### Php-webdriver version

1.15.1

### PHP version

8.1.29

### How do you start the browser driver or Selenium server

Docker

### Selenium server / Selenium Docker image version

selenium/standalone-chrome

### Browser driver (chromedriver/geckodriver...) version

ChromeDriver 126.0.6478.62

### Operating system

Alpine Linux

**Comment by OndraM** [comment] 2024-06-20 13:33
Hi, maybe not related, but I think you should not combine '--headless=new' and '--headless', as the later one could (?) override the first setting. 

The next thing is the `whitelisted-ips`, which looks suspicious.  Is this option needed? Is there any difference if you don't use this value? Or if you use it as `'--whitelisted-ips'` (ie. without the `=""`) part?

**Comment by LaraGastaldi** [comment] 2024-06-20 13:37
hey @OndraM, I tried removing those options but the error remained :/
tried removing all options too and leave only the ::chrome() and it throws the error as well. Very strange

**Comment by OndraM** [comment] 2024-06-20 13:43
:thinking: Another thing is you should use different URL of the selenium server and also different key for the options.

```diff
return RemoteWebDriver::create(
-            'http://selenium:4444/wd/hub',
+            'http://selenium:4444/',
-            desired_capabilities: DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options)
+            desired_capabilities: DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY_W3C, $options)
        );
```

See https://github.com/php-webdriver/php-webdriver/wiki/Chrome#general-usage .

**Comment by LaraGastaldi** [comment] 2024-06-20 13:50
tried both of that and it still throws the error.
I don't understand, I made the dd( )s and the curl gets the response correctly

**Comment by LaraGastaldi** [comment] 2024-06-21 14:25
I identified, it seems like the connection refused occurs in the **delete session call**. 
URL: `http://selenium:4444/wd/hub/session/9953c27121b2b136b1ca316fc52de7b7`
Method: DELETE
`$value` variable comes back null

All other calls (/screenshot, /session/{id}/window/rect, etc) runs perfectly.

I am trying to extend the class to ignore this call's response. I assume there will be many sessions open and I might need to restart the selenium server sometimes.

But this is still a problem, right?

**Comment by LaraGastaldi** [comment] 2024-06-21 14:30
It seems like my selenium server call is crazy slow, php artisan dusk takes absolutely forever to run and shell curl commands are also very slow. This may have something to do?

**Comment by LaraGastaldi** [comment] 2024-06-21 20:14
updating here, in my curl call, it seems like this is an issue with selenium after all. But I can't figure out how to fix it :(

```
root@70ba95839a12:/var/www# curl -X POST --data '{"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}}' http://selenium:4444/wd/hub/session
{
  "value": {
    "error": "session not created",
    "message": "Could not start a new session. New session request timed out \nHost info: host: 'f82541d6971e', ip: '172.23.0.2'\nBuild info: version: '4.21.0', revision: '79ed462ef4'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.6.22-linuxkit', java.version: '17.0.11'\nDriver info: driver.version: unknown",
    "stacktrace": [
      {
        "fileName": "LocalNewSessionQueue.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "addToQueue",
        "className": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue",
        "lineNumber": 221,
        "classLoaderName": "app"
      },
      {
        "fileName": "NewSessionQueue.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$new$0",
        "className": "org.openqa.selenium.grid.sessionqueue.NewSessionQueue",
        "lineNumber": 68,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$TemplatizedRoute",
        "lineNumber": 192,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 69,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 360,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 69,
        "classLoaderName": "app"
      },
      {
        "fileName": "NewSessionQueue.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.grid.sessionqueue.NewSessionQueue",
        "lineNumber": 128,
        "classLoaderName": "app"
      },
      {
        "fileName": "SpanWrappedHttpHandler.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler",
        "lineNumber": 87,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 63,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 360,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 69,
        "classLoaderName": "app"
      },
      {
        "fileName": "Router.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.grid.router.Router",
        "lineNumber": 87,
        "classLoaderName": "app"
      },
      {
        "fileName": "EnsureSpecCompliantResponseHeaders.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders",
        "lineNumber": 34,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 63,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 360,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 69,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$NestedRoute",
        "lineNumber": 270,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 69,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 360,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 69,
        "classLoaderName": "app"
      },
      {
        "fileName": "AddWebDriverSpecHeaders.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.remote.AddWebDriverSpecHeaders",
        "lineNumber": 35,
        "classLoaderName": "app"
      },
      {
        "fileName": "ErrorFilter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.remote.ErrorFilter",
        "lineNumber": 44,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 63,
        "classLoaderName": "app"
      },
      {
        "fileName": "ErrorFilter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.remote.ErrorFilter",
        "lineNumber": 44,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 63,
        "classLoaderName": "app"
      },
      {
        "fileName": "SeleniumHandler.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$channelRead0$0",
        "className": "org.openqa.selenium.netty.server.SeleniumHandler",
        "lineNumber": 44,
        "classLoaderName": "app"
      },
      {
        "fileName": null,
        "moduleVersion": "17.0.11",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "call",
        "className": "java.util.concurrent.Executors$RunnableAdapter",
        "lineNumber": -1,
        "classLoaderName": null
      },
      {
        "fileName": null,
        "moduleVersion": "17.0.11",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "run",
        "className": "java.util.concurrent.FutureTask",
        "lineNumber": -1,
        "classLoaderName": null
      },
      {
        "fileName": null,
        "moduleVersion": "17.0.11",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "runWorker",
        "className": "java.util.concurrent.ThreadPoolExecutor",
        "lineNumber": -1,
        "classLoaderName": null
      },
      {
        "fileName": null,
        "moduleVersion": "17.0.11",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "run",
        "className": "java.util.concurrent.ThreadPoolExecutor$Worker",
        "lineNumber": -1,
        "classLoaderName": null
      },
      {
        "fileName": null,
        "moduleVersion": "17.0.11",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "run",
        "className": "java.lang.Thread",
        "lineNumber": -1,
        "classLoaderName": null
      }
    ]
  }
```

**Comment by OndraM** [comment] 2024-11-21 15:03
As this is probably outdated and not able to reproduce, I'm closing this. If the problem persist, please reopen the issue or open a new one, and do not forget to provide current exact Chrome and Chromedriver version. Thanks!

**Closed by OndraM** 2024-11-21 15:03 UTC
Labels: bug, waiting for reaction
