### ISSUE TITLE
Process management

### ISSUE THREAD

**Issue by kenygamer** [php-webdriver/php-webdriver#871] opened 2021-03-11 00:27 UTC
### Bug description

Hello,
It has come to my attention that every hour, my process list grows massively, until it becomes opaque with `/usr/lib/chromium-browser` processes. I wonder what is the process management for this PHP library since the process does not terminate in every loop of the PHP script.

### How could the issue be reproduced

```php
$serverUrl = "http://localhost:4444/";
$desiredCapabilities = DesiredCapabilities::chrome();
$this->webdriver = RemoteWebDriver::create($serverUrl,
$desiredCapabilities);
```

### Details

* Php-webdriver version: 1.10.0
* PHP version: 8.0.0
* How do you start the browser: Chromedriver
* Selenium server version: I'm sorry, but where do I find this? In the guide it said to install chromium-browser, and this is how I left it to a working state.
* Operating system: Ubuntu 20.04.2 LTS
* Browser used + version: chromium-browser:amd64/bionic-security 87.0.4280.66-0ubuntu0.18.04.1 uptodate
* Browser driver (chromedriver/geckodriver...) version: I'm sorry, but where do I find this? In the guide it said to install chromium-browser, and this is how I left it to a working state.

**Comment by OndraM** [comment] 2021-03-11 01:00
Hi,

> Browser driver (chromedriver/geckodriver...) version: I'm sorry, but where do I find this? In the guide it said to install chromium-browser, and this is how I left it to a working state.

Try to run `chromedriver --version` in your shell.

>  I wonder what is the process management for this PHP library since the process does not terminate in every loop of the PHP script.

What is the code you use for the "loop"? How do you execute your scripts?

Also, could you please provide whole script you run (from start to end)? The provided snippet is not enough for us to reproduce the issue.

Thanks

**Comment by kenygamer** [comment] 2021-03-11 21:26
@OndraM 1. When I try to use this command, I get the following error:
```
chromedriver: command not found
```

2.  I execute my script in CLI. The script may or may not be killed, may or may not exit normally. 

3.
```php
<?php

class Test{
    private bool $exit = false;
    private $driver = null;

    public function __construct(){
        $this->exit = boolval(mt_rand(0, 1));
    }
     
    private function stopDriver(){
        if($this->driver !== null){
            $this->driver->quit();
            $this->driver = null;
         }
      }

    private function restartDriver(){
        $this->stopDriver();
        $serverUrl = "http://localhost:4444/";
        $desiredCapabilities = DesiredCapabilities::chrome();
        $this->driver = RemoteWebDriver::create($serverUrl,
$desiredCapabilities);
    }

    public function run(){
       while(true){
           $this->restartDriver();
           $this->get("https://www.google.com/");
       }
    }

    public function __destruct(){
        $this->stopDriver();
    }

$test = new Test();
$test->run();
    
```

**Comment by OndraM** [comment] 2021-03-11 22:28
There must be `chromedriver` binary somewhere on the system which runs the browser. On ubuntu this is probably `/usr/lib/chromium-browser/chromedriver`. 

And how do you start the browsers? There must be something listening on the $serverUrl - what is it? Do you use Selenium server / Docker images ...? If you could, pleas provide the full command you run, and versions of these components. And also their logs or output they provide.

However - as you use `RemoteWebDriver::create($serverUrl, $desiredCapabilities);` to connect to the browser driver, the php-webdriver is not directly managing any other process.  Starting browser instances is up to Selenium server / chromedriver (depending on what you use).

**Comment by kenygamer** [comment] 2021-03-12 18:28
1. Chromedriver 87.0.4280.66
2. I use the same exact code as I sent. I first start the chromedriver manually, before running the script.
3. I don't use Selenium or Docker images.
4. Here are the chromedriver logs:

```
Starting ChromeDriver 87.0.4280.66 (fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1615573101.468][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573101.468][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573162.446][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573162.446][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573222.553][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573222.553][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
```
5. Here is `htop` after a few minutes:
 ![](https://i.ibb.co/6Bxd72m/1-A635080-4304-4-E70-885-C-D0-F172294-DBF.jpg)

It is such a point that my server is saturated that all my other processes are killed.

**Comment by kenygamer** [comment] 2021-03-12 18:28
1. Chromedriver 87.0.4280.66
2. I use the same exact code as I sent. I first start the chromedriver manually, before running the script.
3. I don't use Selenium or Docker images.
4. Here are the chromedriver logs:

```
Starting ChromeDriver 87.0.4280.66 (fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1615573101.468][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573101.468][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573162.446][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573162.446][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573222.553][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1615573222.553][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
```
5. Here is `htop` after a few minutes:
 ![](https://i.ibb.co/6Bxd72m/1-A635080-4304-4-E70-885-C-D0-F172294-DBF.jpg)

It is such a point that my server is saturated that all my other processes are killed.

**Comment by JuGid** [comment] 2021-03-13 00:40
I permit myself to answer because I had a related problem.

For your issue, did you try to use $driver->close() then $driver->quit(). This solved my issue after lot of Google requests. 
```php
private function stopDriver(){
    if($this->driver !== null){
        $this->driver->close();
        $this->driver->quit();
        $this->driver = null;
    }
}
```

**Comment by kenygamer** [comment] 2021-03-13 16:53
> I permit myself to answer because I had a related problem.
> 
> Did you try to use $driver->close() then $driver->quit(). This solved my issue after lot of Google search.
> 
> ```
> private function stopDriver(){
>     if($this->driver !== null){
>         $this->driver->close();
>         $this->driver->quit();
>         $this->driver = null;
>     }
> }
> ```
Sorry, it does not solve my problem.

**Comment by kenygamer** [comment] 2021-03-13 16:54
@JuGid Sorry, that didn't work out.

**Comment by OndraM** [comment] 2021-03-18 17:36
Hi, thanks for the information.

Just to be sure, you start chromedriver by running
`chromedriver --port=4444`
and the script by running
`php script.php`

Is this right?

Also, I don't fully understand the `$this->exit = boolval(mt_rand(0, 1));` etc. part in the script, what is it purpose, is it relevant to show the issue?

I tried to reproduce it and running the script: however using latest Chrromedriver (v89) the number of chromium processes was not increasing, and when the script was ended, all the processes crated by chromedriver were terminated. 

So maybe try using latest chromedriver - otherwise this does not seem like php-webdriver issue, could be a bug in chromedriver.

**Comment by kenygamer** [comment] 2021-04-06 21:24
> Hi, thanks for the information.
> 
> Just to be sure, you start chromedriver by running
> `chromedriver --port=4444`
> and the script by running
> `php script.php`
> 
> Is this right?
> 
> Also, I don't fully understand the `$this->exit = boolval(mt_rand(0, 1));` etc. part in the script, what is it purpose, is it relevant to show the issue?
> 
> I tried to reproduce it and running the script: however using latest Chrromedriver (v89) the number of chromium processes was not increasing, and when the script was ended, all the processes crated by chromedriver were terminated.
> So maybe try using latest chromedriver - otherwise this does not seem like php-webdriver issue, could be a bug in chromedriver.
Hello,

Yes. That's right. I am starting chromedriver by specifying the port manually.

My chromebrowser version 87.

I am using the condition to try to replicate unexpected script termination. Which seems to help reproduce the issue.

**Comment by OndraM** [comment] 2021-04-06 22:19
Ok, so please try in the latest chrome + chromedriver version (which is 89).

> I am using the condition to try to replicate unexpected script termination. Which seems to help reproduce the issue.

But from what I see, this is not exactly what the code does. This does terminate the script after first run in 50 % cases. And after it is terminated, it obviously cannot create any more browser instances and you cannot test anything, it just stops. 

If the issue persists even when using the latest chrome and latest chromedriver, could you please try to provide minimal reproducible script (ie. remove everything that is not needed to show the issue) - it will help locating the core issue.

Thanks and good luck :)

**Comment by kenygamer** [comment] 2021-04-07 18:27
have tried using the latest chrome + chromedriver version. The issue persists.

**Comment by kenygamer** [comment] 2021-04-09 19:51
@OndraM

**Comment by OndraM** [comment] 2021-04-11 15:04
> I have tried using the latest chrome + chromedriver version. The issue persists.

But you didn't provide a simple reproducible script for this issue - we are unable to dig into this any deeper. I tried your original script and was not able to reproduce the issue.

So I'm closing this for now - nothing so far showed there is some incorrect behavior of php-webdriver. And from the characteristics of it there is really low chance this is an issue of php-webdriver, because `chromium-browser` processes are started and taken care of by chromedriver, not by php-webdriver.

And if there is some issue with chromedriver memory leaks, it would have to be [reported directly](https://chromedriver.chromium.org/help) to chromedriver team.

Thanks for your understanding!

**Closed by OndraM** 2021-04-11 15:04 UTC
Labels: bug
