### ISSUE TITLE
WebDriver fails to detect alert in more complex DOM Trees

### ISSUE THREAD

**Issue by jpastuszuk** [php-webdriver/php-webdriver#656] opened 2019-08-04 14:02 UTC
### What are you trying to achieve? (Expected behavior)
Test website for presence of alert messages

### What do you get instead? (Actual behavior)
Falsy behavior when site contains elements such us inline `<style>` or more complicated DOM Tree

### How could the issue be reproduced? (Steps to reproduce)
When presenting simple page to webdriver (for example only with `<script>alert(1)</script>` tag, script does correctly check for alert presence

on the other hand, embedding script in more complex DOM Tree (such as this Bootstrap Snippet: https://bootsnipp.com/snippets/RE68M) makes script fail to detect alert.

Alert is still present in user browser

I had situations in which alert is not correctly detected by script, but removing only inline css style (it might be only 1 line) ended in changing script behavior to correct again.

```php
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::chrome();

$options = new ChromeOptions();

// all options required to work
$options->addArguments(array(
    "--headless", "window-size=1024,768", "--no-sandbox"
));
$prefs = array(
    'permissions.default.stylesheet' => 2,
    'permissions.default.image' => 2
);
$options->setExperimentalOption('prefs', $prefs);
$capabilities->setCapability(ChromeOptions::CAPABILITY, $options);
$driver = RemoteWebDriver::create($host, $capabilities, 5000);

$driver->get("url");

function isAlertPresent($driver){
    $presentFlag = false;

    try{
        $driver->wait(10)->until(WebDriverExpectedCondition::alertIsPresent());
        $driver->switchTo()->alert()->accept();
        $presentFlag = true;
    }
    catch (Exception $ex){}

    return $presentFlag;
}

$alert_is_present = isAlertPresent($driver);
// close the browser
$driver->quit();
```

Example of HTML file: https://gist.github.com/jpastuszuk/fc6dff861a75c1588345792bb69b3820

In this state, Result of check fo alert will be False
Removing/commenting only style tags will result in correct Alert detection (true)

### Details

* Php-webdriver version: 1.7.1
* PHP version: 7.2.19
* Selenium server version: 3.9.1
* Operating system: Mac OS Mojave/ Ubuntu 18.10
* Browser used + version: ChromeDriver 76.0.3809.68 / Google Chrome 76.0.3809.87

**Comment by andrewnicols** [comment] 2020-02-03 23:56
Sorry @jpastuszuk, but I canot reproduce this. I suspect that there is an issue with your page or the version of chrome that you were testing with.

I've tested using the example HTML file provided, and the following test script:
https://gist.github.com/5f6c26bbc483bcdd84387f124bc2476b

@OndraM, Suggest closing as I cannot reproduce on 1.7.1.

**Closed** 2020-02-06 15:32 UTC
