### ISSUE TITLE
Can't simulate insertion of @-symbol using keyDown(ALT) + sendKeys('2') using ChromeDriver

### ISSUE THREAD

**Issue by cjohansson** [php-webdriver/php-webdriver#967] opened 2022-02-14 12:27 UTC
### Bug description

A workaround for [issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999) in Chromedriver is to replace `sendKeys('a@b.com')` with `sendKeys('a'); keyDown('ALT'); sendKeys('2'); keyUp('ALT'); sendKeys('b.com');` but I can't get this to work with php-webdriver. I am using `php-webdriver` 1.1.3. (In my Swedish keyboard I need to press ALTGR (CTRL + ALT) and 2 to insert the @-symbol.)

### How could the issue be reproduced

Following code should insert a @-symbol in the element represented by $emailElement but it does not

```php
    use Facebook\WebDriver\Remote\DesiredCapabilities;
    use Facebook\WebDriver\Remote\RemoteWebDriver;
    use Facebook\WebDriver\WebDriverBy;

    // Input @ character
    $serverUrl = 'http://localhost:4444';

    $capabilities = DesiredCapabilities::chrome();
    $capabilities->setCapability('acceptInsecureCerts', true);

    // Chrome
    $driver = RemoteWebDriver::create(
        $serverUrl,
        $capabilities
    );
    $emailElement =
        $driver->findElement(WebDriverBy::cssSelector('input#billing_email'));
    $webDriverActions = new \Facebook\WebDriver\Interactions\WebDriverActions(
        $driver
    );
    $webDriverActions->keyDown(
        $emailElement,
        \Facebook\WebDriver\WebDriverKeys::CONTROL
    );
    $webDriverActions->keyDown(
        $emailElement,
        \Facebook\WebDriver\WebDriverKeys::LEFT_ALT
    );
    $webDriverActions->sendKeys(
        $emailElement,
        '2'
    );
    $webDriverActions->keyUp(
        $emailElement,
        \Facebook\WebDriver\WebDriverKeys::CONTROL
    );
    $webDriverActions->keyUp(
        $emailElement,
        \Facebook\WebDriver\WebDriverKeys::LEFT_ALT
    );
    $webDriverActions->perform();

```

**Comment by OndraM** [comment] 2022-08-25 14:39
Hi, I was unable to reproduce the issue. I don't use swedish keyboard :) , but for example this works for english one:

```php
$webDriverActions->keyDown($element, WebDriverKeys::SHIFT);
$webDriverActions->sendKeys($element, '2');
$webDriverActions->keyUp($element, WebDriverKeys::SHIFT);
```

... and inserts `@` into the element. Also the original Chromedriver 98 issue seems to be resolved now, so closing this issue. If the issue is still present please feel free to reopen it or create a new one. Thanks!

**Closed by OndraM** 2022-08-25 14:39 UTC
Labels: bug

**Comment by cjohansson** [comment] 2022-08-26 06:02
Thanks for the follow-up, this resolved itself when Chromdriver updated itself
