### ISSUE TITLE
Symfony 5 Process support

### ISSUE THREAD

**Issue by aykonsvk** [php-webdriver/php-webdriver#742] opened 2020-01-30 09:19 UTC
### What are you trying to achieve? (Expected behavior)
I'm trying to install package using composer.

### What do you get instead? (Actual behavior)
Package is not installed because of dependencies

### How could the issue be reproduced? (Steps to reproduce)
Install Symfony 5 framework try to install php-webdriver

 - php-webdriver/webdriver 1.7.1 requires symfony/process ^2.8 || ^3.1 || ^4.0 -> no matching package found.

### Details
* Php-webdriver version:  1.7.1 
* PHP version:  7.4.2 (cli)
* Selenium server version: -
* Operating system: Mac Catalina

**Comment by OndraM** [comment] 2020-02-02 23:26
Duplicate of #670, #712, #736 .

See https://github.com/php-webdriver/php-webdriver/issues/712#issuecomment-566085763 for temporary workaround.

**Closed by OndraM** 2020-02-02 23:26 UTC
