### ISSUE TITLE
With 4.18.1-20240224 I get a DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by elnath78** [php-webdriver/php-webdriver#1094] opened 2024-03-10 19:38 UTC
### Bug description

Fatal error: Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: DevToolsActivePort file doesn't exist Host info: host: 'd1a93cda54a8', ip: '172.18.0.5' Build info: version: '4.18.1', revision: 'b1d3319b48' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-25-generic', java.version: '11.0.21' Driver info: driver.version: unknown Build info: version: '4.18.1', revision: 'b1d3319b48' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-25-generic', java.version: '11.0.21' Driver info: driver.version: unknown Build info: version: '4.18.1', revision: 'b1d3319b48' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-25-generic', java.version: '11.0.21' Driver info: driver.version: unknown in C:\xampp\htdocs\redacted\vendor\php-webdriver\webdriver\lib\Exception\WebDriverException.php on line 130

### How could the issue be reproduced

```shell
//Set Up Chrome Options
$chromeOptions = new ChromeOptions();
$chromeOptions->setExperimentalOption('w3c', false);
$chromeOptions->addArguments($args);
//Set Capabilities
$seleniumCapabilities = DesiredCapabilities::chrome();
$seleniumCapabilities->setCapability('acceptSslCerts', false);
//Create Selenium Connection
$driver = RemoteWebDriver::create($seleniumHost, $seleniumCapabilities);
//Go To URL
$url="https://en.wikipedia.org/wiki/Selenium_(software)";
$driver->navigate()->to($url);
//Exit, do nothing just pray connection works
$driver->quit();
```

### Expected behavior

I'd be happy if I can set a connection, would be a great upgrade.

### Php-webdriver version

1.15.1

### PHP version

8.2.0

### How do you start the browser driver or Selenium server

selenium in docker

### Selenium server / Selenium Docker image version

4.18.1-20240224

### Browser driver (chromedriver/geckodriver...) version

where should I run this?

### Browser name and version

where should I run this?

### Operating system

Ubuntu

### Additional context

```yml
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.18.1-20240224
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

**Comment by elnath78** [comment] 2024-03-10 22:26
I did a try with `https://github.com/php-webdriver/php-webdriver/blob/main/example.php` this time I got a `Fatal error: Maximum execution time of 120 seconds exceeded in C:\xampp\htdocs\redacted\vendor\php-webdriver\webdriver\lib\Remote\HttpCommandExecutor.php on line 325` with the stack trace pointing at `\RemoteWebDriver.php:129`

I forgot to mention I have a `cd /opt/selenium/ && docker-compose up -d` set in my `crontab` with a `@reboot` directive to start selenium when I need to reboot, I noticed in the comments I'm supposed to use `-f` not sure if this could complicate things up.

**Comment by elnath78** [comment] 2024-03-11 03:59
**edit** Adding `user:` directive in the `.yml` file didnt help, I have read this would have fixed the bug, but not in my case.

**Comment by OndraM** [comment] 2024-03-11 11:17
Hi,
1) Do not disable w3c mode (ie. remove `$chromeOptions->setExperimentalOption('w3c', false);`) . What is the reason for this? The old mode is deprecated an may not work properly.
2) If it won't help, try disabling sandbox mode in Chrome:
```php
$chromeOptions = new ChromeOptions();
$chromeOptions->addArguments(['--no-sandbox']);
$chromeOptions->addArguments($args);
// ...
```

Also, this is probably not a bug in php-webdriver, but behavior of Chromedriver... And there is already a discussion thread for this: https://github.com/php-webdriver/php-webdriver/discussions/964

**Comment by elnath78** [comment] 2024-03-11 12:05
@OndraM Hi, I have updated in a comment I'm now using `https://github.com/php-webdriver/php-webdriver/blob/main/example.php` to test it with a working sample, and I'm getting a `Fatal error: Maximum execution time of 120 seconds exceeded in C:\xampp\htdocs\redacted\vendor\php-webdriver\webdriver\lib\Remote\HttpCommandExecutor.php on line 325`

**Comment by OndraM** [comment] 2024-03-11 13:48
Please, try to reproduce the issue in the minimal setup possible.

Could you please:
- Provide the command(s) you use to start docker
- Provide the command you use to start the PHP script
- Provide exactly the full PHP script you run

**Comment by elnath78** [comment] 2024-03-11 15:27
>  Provide the command(s) you use to start docker

`docker-compose up` inside the folder with `.yml` file

> * Provide the command you use to start the PHP script

I open the web browser and navigate to the script page.

> Provide exactly the full PHP script you run
`https://github.com/php-webdriver/php-webdriver/blob/main/example.php`

**Comment by OndraM** [comment] 2024-03-11 15:40
> > * Provide the command you use to start the PHP script
> 
> I open the web browser and navigate to the script page.

What does it mean exactly, could you elaborate please? How you run the "example.php" script?

**Comment by elnath78** [comment] 2024-03-11 16:07
> What does it mean exactly, could you elaborate please? How you run the "example.php" script?

What is not clear in I open my browser and navigate? I type in the address in the browser.

**Comment by OndraM** [comment] 2024-03-11 16:29
Well, this is not a way to run such PHP script. You should be running it from command line using `php`, not through web-server - this could be the cause of the issue.

If the selenium is stared on you machine (and you can open http://localhost:4444 to see selenium dashboard), then you can run the script from the command line like this:
```sh
php example.php
```

**Comment by OndraM** [comment] 2024-03-12 09:15
Ok, good to hear. 

But from all this I don't see there an bug in php-webdriver, so closing this issue.

**Closed by OndraM** 2024-03-12 09:15 UTC
Labels: bug

**Comment by elnath78** [comment] 2024-03-12 12:42
@OndraM The bug persist, it has not been resolved, just hidden under the rug. If you replicate my setup described above you will be able to replicate also the bug.

**Comment by elnath78** [comment] 2024-03-13 12:11
@OndraM did you use this from an external device? In my setup I was on `XAMPP` (php) and the docker-selenium was on a Ubuntu VPS with firewall port 4444 open for TCP inbound.

**Comment by OndraM** [comment] 2024-03-15 10:21
@elnath78 No, I tried it locally.

You are describing quite unusual setup, which is another lead to believe this is issue with your setup, not this library. And I am unable to help you with that, sorry.
