### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by alissonlinneker** [php-webdriver/php-webdriver#811] opened 2020-08-01 16:32 UTC
How to add Headers to the requisition?

I am using the --proxy-server parameter and need to add "X-" headers to the request to be processed by the server, before going to the destination URL.

I didn't find anything specifying.

Any solution?

**Comment by dunglas** [comment] 2020-08-03 17:12
It's not possible. The WebDriver spec doesn't allow it. Actually the WebDriver spec is designed as if you were using a browser directly (as a user), and it's not possible to set custom HTTP headers using the UI of a web browser.

However, you can configure the web browser that will be managed by WebDriver, set proxy servers to use and even install browser extensions.

**Comment by alissonlinneker** [comment] 2020-08-03 20:31
> It's not possible. The WebDriver spec doesn't allow it. Actually the WebDriver spec is designed as if you were using a browser directly (as a user), and it's not possible to set custom HTTP headers using the UI of a web browser.
> 
> However, you can configure the web browser that will be managed by WebDriver, set proxy servers to use and even install browser extensions.

What is the recommended extension to change the headers before sending the request?

**Comment by OndraM** [comment] 2020-08-03 23:34
(Duplicate of #368.)

> What is the recommended extension to change the headers before sending the request?

To use proxy to modify headers have a look at https://github.com/lightbody/browsermob-proxy .

Or you can try to install some extension when starting the browser (using eg. `ChromeOptions::addExtension()`) and modify the headers using the extension. But I have no experience with this. For example https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj or any other "modify headers"-capable extension.

**Closed** 2020-08-04 09:15 UTC
Labels: duplicate
